### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by roadlittledawn** [roadlittledawn/portfolio-site#14]
# Checklist

## Career data
- [x] Update experience info

## Logo
- [ ] Add new logo
- [x] Update favicon
- [ ] Ensure logo shows on mobile nav

## Experience page
- [x] Add timeline view
- [ ] Add company logos

## Run tests
- [x] Run lighthouse test w/focus on accessibility

## General style
- [ ] Remove unneeded colors, theme vars
